name: CI Pipline

on: push

jobs:
  build:
    name: Building App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: install dependecies
        run: npm install

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    name: testing App
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tests
        run: npm run test -- --coverage

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
